# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sharp-summit
email: summit7ca@163.com
mobile: +86 15055168824
job: .NET Development Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://summit7ca.oschina.io" # the base hostname & protocol for your site

# Build settings
# markdown: kramdown
# relative_permalinks: false
# permalink: /:categories/:title/

# Posts settings
# future: true
# safe: false
# lsi: false
# excerpt_separator: "\n\n"

# Theme settings
# compress_html:
#   comments: ["<!-- ", " -->"]
#   clippings: all
#   endings: all


sass:
  sass_dir: assets/_sass
  style: compressed

# images: '/assets/images'
