# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sharp-summit
email: summit7ca@163.com
mobile: +86 15055168824
job: .NET Development Engineer
baseurl: "/sharp-resume" 
url: "http://summit7ca.oschina.io"

# safe: true  禁用插件

sass:
  sass_dir: assets/_sass
  style: compressed